import Link from "next/link";
import React from "react";
import Legal, {
	LegalList,
	LegalMail,
	LegalSection,
} from "@/components/Legal";
import { LEGAL, PRIVACY_EMAIL, SUPPORT_EMAIL } from "@/types";

const PolicyPage = () => (
	<Legal
		title="Privacy Policy"
		description="How Ubuntu Health handles practice, practitioner and patient information under POPIA."
	>
		<LegalSection heading="1. Who this policy covers">
			<p>
				This policy explains how {LEGAL.entity} ({LEGAL.registrationNumber}),{" "}
				{LEGAL.address}, handles personal information in the Ubuntu Health web
				application and API.
			</p>
			<p>
				Under the Protection of Personal Information Act (POPIA) we hold two
				different roles, and it matters which one applies:
			</p>
			<LegalList
				items={[
					"For patient records, your practice is the responsible party and we are your operator. Your practice decides what is captured and why. We process those records only to run the service for you, on your instruction.",
					"For practice and user accounts, meaning the details of the practice itself and the people who sign in, we are the responsible party.",
				]}
			/>
		</LegalSection>

		<LegalSection heading="2. What we hold">
			<p>Account and practitioner information, which we collect from you:</p>
			<LegalList
				items={[
					"Name, email address and phone number.",
					"Practice name, practice phone number and the role held in the practice.",
					"HPCSA registration number and specialty, for practitioners.",
					"A hashed password. We never store passwords in a readable form.",
				]}
			/>
			<p>
				Patient records, which your practice captures and which are health
				information, treated as special personal information under POPIA:
			</p>
			<LegalList
				items={[
					"Patient name, South African identity number, sex, contact details and physical address.",
					"Medical aid scheme name and membership number.",
					"Allergies and current medication.",
					"Emergency contact name, phone number and relationship.",
					"Clinical notes, including diagnosis codes and free text written by the practitioner.",
					"Prescriptions, including medication, dosage, frequency, instructions, refills and the prescribing practitioner.",
					"Appointments, including date, time, type, status and booking notes.",
					"Invoices, including amounts, status and notes.",
				]}
			/>
			<p>Technical information, which is generated by using the service:</p>
			<LegalList
				items={[
					"Request logs holding the method, path, practice identifier and timestamp, used for security and fault diagnosis.",
					"IP addresses and connection metadata, processed by our hosting providers.",
				]}
			/>
		</LegalSection>

		<LegalSection heading="3. Cookies">
			<p>
				We set one cookie, named access_token. It holds your signed in session,
				it is marked HttpOnly so that scripts in the browser cannot read it, and
				it is sent only over HTTPS. It is strictly necessary: without it you
				cannot stay signed in.
			</p>
			<p>
				We run no analytics, advertising, profiling or tracking cookies, and we
				embed no third party trackers.
			</p>
		</LegalSection>

		<LegalSection heading="4. How we use information">
			<LegalList
				items={[
					"To provide the service: storing and returning your practice's records, and keeping each practice's data separate from every other practice.",
					"To authenticate users and apply the role permissions your administrator has set.",
					"To enforce plan limits, such as the number of practitioner seats in use.",
					"To provide support when you ask for it.",
					"To protect the service, including investigating suspicious access and faults.",
					"To bill your practice and send service notices, such as changes to these documents.",
				]}
			/>
			<p>
				We do not sell personal information, we do not share it with
				advertisers, and we do not use patient records to train machine learning
				models.
			</p>
		</LegalSection>

		<LegalSection heading="5. Our lawful basis">
			<p>
				We process account information to perform our contract with your
				practice and to meet our legal obligations. We process patient records
				on your practice&apos;s authorisation as its operator.
			</p>
			<p>
				Health information is special personal information. POPIA permits it to
				be processed by, or on behalf of, health care professionals where this
				is necessary for treatment and the person processing it is under a duty
				of confidentiality. Your practice is responsible for the patient consent
				and confidentiality obligations that attach to the records it captures,
				and we handle those records under a duty of confidentiality to your
				practice.
			</p>
		</LegalSection>

		<LegalSection heading="6. Who else processes your data">
			<p>
				We keep the list of providers short, and we use each of them only to run
				the service:
			</p>
			<LegalList
				items={[
					"Vercel, which hosts and delivers the web application.",
					"Render, which hosts the API.",
					"Neon, which provides the managed PostgreSQL database where your records are stored.",
				]}
			/>
			<p>
				These providers act as our operators, under agreements that limit them
				to processing data on our instruction. We add no other recipients. In
				particular, the service sends no email at all: staff invitations are
				links that your administrator shares directly, and we never contact your
				patients.
			</p>
			<p>
				We will also disclose information where the law compels it, for example
				under a valid court order, and we will tell you unless we are prohibited
				from doing so.
			</p>
		</LegalSection>

		<LegalSection heading="7. Where your data is stored">
			<p>
				Our hosting and database providers operate outside South Africa. This
				means personal information, including patient records, is transferred
				across the border within the meaning of section 72 of POPIA. We rely on
				the data processing agreements we hold with those providers, which bind
				them to standards of protection substantially similar to POPIA, and
				which prohibit onward transfer to anyone who is not similarly bound.
			</p>
		</LegalSection>

		<LegalSection heading="8. How we protect it">
			<LegalList
				items={[
					"All traffic runs over HTTPS, and the API redirects insecure requests.",
					"Passwords are hashed by ASP.NET Core Identity and must be at least twelve characters.",
					"Session tokens live in an HttpOnly, Secure cookie rather than in browser storage.",
					"Every request is scoped to the practice identifier carried in the session, so one practice cannot read another practice's records.",
					"Role permissions limit what each user can reach: reception cannot open clinical notes, and only administrators can manage staff or billing.",
					"A deactivated user is rejected when their session is validated, even if they still hold a token.",
					"Access to the production database is limited to the people who need it to operate the service.",
				]}
			/>
			<p>
				No system is perfectly secure. We do not yet hold an independent security
				certification such as ISO 27001, and we do not claim one.
			</p>
		</LegalSection>

		<LegalSection heading="9. How long we keep it">
			<p>
				We keep your records for as long as your practice has an account. After
				cancellation we keep them for {LEGAL.retentionDays} days so that you can
				still request an export, and we then delete them. Technical logs are
				kept for a shorter period, only as long as they are useful for security
				and diagnosis.
			</p>
			<p>
				The legal duty to retain patient records sits with your practice, not
				with us. HPCSA guidance generally requires records to be kept for at
				least six years from the last consultation, and longer for minors and
				for certain categories of record. Export your records and store them
				before you cancel.
			</p>
		</LegalSection>

		<LegalSection heading="10. Patient requests">
			<p>
				A patient who wants to access, correct or delete their record should
				contact the practice that treats them. The practice holds the clinical
				relationship, and it decides what happens to the record. If we receive a
				request directly from a patient, we will refer them to the practice and
				tell the practice about it.
			</p>
			<p>
				Practices can act on those requests themselves: patient details can be
				corrected or deleted from the patient record in the application.
			</p>
		</LegalSection>

		<LegalSection heading="11. Your rights as a user">
			<p>
				Under sections 23 and 24 of POPIA you may ask what personal information
				we hold about you, ask us to correct or delete information that is
				inaccurate or excessive, and object to processing. Write to{" "}
				<LegalMail address={PRIVACY_EMAIL} />. We will respond within a
				reasonable period, and we may need to verify who you are first.
			</p>
			<p>
				You can update your own name, contact details, HPCSA registration number
				and specialty from your profile page at any time.
			</p>
		</LegalSection>

		<LegalSection heading="12. Getting your data out">
			<p>
				Any administrator can export the practice&apos;s full record set, which
				covers staff, patients, appointments, clinical notes, prescriptions and
				invoices, as a JSON file from the Billing page. The export stays
				available while the account exists, including after a trial has ended
				and during read only mode. See our{" "}
				<Link
					href="/terms"
					className="text-foreground underline-offset-4 hover:underline"
				>
					Terms of Service
				</Link>{" "}
				for what happens to your data when you cancel.
			</p>
		</LegalSection>

		<LegalSection heading="13. Security incidents">
			<p>
				If we have reasonable grounds to believe that personal information has
				been accessed or acquired by an unauthorised person, we will notify the
				Information Regulator and the affected practices as soon as reasonably
				possible, as section 22 of POPIA requires. Where we act as your
				operator, we will notify your practice without undue delay so that you
				can meet your own notification duties to patients.
			</p>
		</LegalSection>

		<LegalSection heading="14. Children">
			<p>
				The service is for health care professionals, and it is not intended for
				use by children. Records of patients under eighteen are captured by the
				practice, and the practice is responsible for obtaining consent from a
				parent or guardian where POPIA requires it.
			</p>
		</LegalSection>

		<LegalSection heading="15. Marketing">
			<p>
				We send service messages, such as billing notices and changes to these
				documents. We do not send unsolicited marketing to your patients, and we
				never use patient contact details for our own marketing.
			</p>
		</LegalSection>

		<LegalSection heading="16. Changes to this policy">
			<p>
				We may update this policy. The new version appears on this page with a
				new last updated date, and we notify practice administrators of material
				changes.
			</p>
		</LegalSection>

		<LegalSection heading="17. Contact and complaints">
			<p>
				Privacy questions: <LegalMail address={PRIVACY_EMAIL} />. Anything else:{" "}
				<LegalMail address={SUPPORT_EMAIL} />. Postal address: {LEGAL.entity},{" "}
				{LEGAL.address}.
			</p>
			<p>
				If we do not resolve your complaint, you may lodge it with the
				Information Regulator (South Africa), whose contact details are
				published at inforegulator.org.za.
			</p>
		</LegalSection>
	</Legal>
);

export default PolicyPage;
